### ISSUE TITLE
Can I make this work in Angular ?

### ISSUE THREAD

**Issue by jasenkabalac** [DylanPiercey/local-devices#17]
I tried to implement and I get an error

ERROR in ./node_modules/mz/child_process.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\NebojsaBalac\lan-scan\node_modules\mz'
ERROR in ./node_modules/local-devices/src/index.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\NebojsaBalac\lan-scan\node_modules\local-devices\src'
ERROR in ./node_modules/ip/lib/ip.js
Module not found: Error: Can't resolve 'os' in 'C:\Users\NebojsaBalac\lan-scan\node_modules\ip\lib'
ERROR in ./node_modules/local-devices/src/index.js
Module not found: Error: Can't resolve 'os' in 'C:\Users\NebojsaBalac\lan-scan\node_modules\local-devices\src'

**Comment by RajithaKumara** [comment]
@jasenkabalac I think you cannot use `local-devices` on browser since this packege needs Node.js core module [`child_process`](https://nodejs.org/api/child_process.html).

**Comment by natterstefan** [comment]
Hi @jasenkabalac,

@RajithaKumara is right, it's not designed to be used in a browser. I am sorry.
