### ISSUE TITLE
NPM Publish to include windows support?

### ISSUE THREAD

**Issue by HenrikJoreteg** [DylanPiercey/local-devices#19]
Hello, @DylanPiercey! thanks for this great module, I was about to send a PR to fix windows support only to see that you already merged a PR that fixes it 😄 

Anyway, it seems the version that is on `npm` doesn't include this fix. Would you be willing to publish an update?

Normally I'm a mac user but happen to be working on an electron.js project where we want to use this module to scan for local network devices on both mac/windows.

Thanks again for this great tool ❤️

**Comment by natterstefan** [comment]
Hi @HenrikJoreteg,

thanks for the feedback :) Happy to hear you like it. I just published [a new version on npm](https://www.npmjs.com/package/local-devices). [It includes the fix](https://github.com/DylanPiercey/local-devices/blob/master/CHANGES.md#300---2019-10-29) you mentioned.

Let us know if it works. Thank you!

**Comment by HenrikJoreteg** [comment]
Awesome, thanks! 👍
