### ISSUE TITLE
Howto Search by Partial Mac Address

### ISSUE THREAD

**Issue by darioajr** [DylanPiercey/local-devices#20]
I need search in my network all raspberry pi devices, the mac address begin with b8:27:eb........

**Comment by natterstefan** [comment]
Hi @darioajr,

currently, this is not possible with our package, but it could definitely be an interesting feature for us. Feel free to contribute by creating a PR including this idea.

You could run `arp -na` for instance and parse the result accordingly. Example output on macOS:

<img width="457" alt="Screenshot 2019-11-19 at 21 30 45" src="https://user-images.githubusercontent.com/1043668/69183785-eb688080-0b13-11ea-970b-031302f85bb7.png">

----

Or you need to figure out how to use these commands in your node app to make it work:

1. install `nmap` and run the following command: `sudo nmap -sP 192.168.0.0/24 | awk '/^Nmap/{print}/B8:27:EB/{print}'`
2. on MacOS `arp -na | grep -i b8:27:eb` or Linux `arp -a | findstr b8-27-eb`

Sources:

- https://www.theurbanpenguin.com/find-my-raspberry-pi-using-nmap/
- https://raspberrypi.stackexchange.com/a/13937/36440
- https://raspberrypi.stackexchange.com/a/34594/36440
