### ISSUE TITLE
Config which IP ranges to scan

### ISSUE THREAD

**Issue by Miosame** [DylanPiercey/local-devices#22]
Currently it scans all subnets connected to the device, but that might not always be useful and take much more time (20 seconds versus ~2-3) than necessary, it would be nice if you could specify a range or subnet at the very least, with something like: https://www.npmjs.com/package/get-ip-range to combat that lengthy scan.

**Comment by natterstefan** [comment]
Hi @Miosame, sounds promising and could be of interest for others. Feel free to try to add this to the library yourself. It might take a little until I get to try it.

**Comment by Miosame** [comment]
@natterstefan the change looks easy (in the .js version), so I will give it a try once I have some free minutes soon'ish, but I never worked with typescript side of things, so hopefully that won't be too much to read on, just for such small change.

**Comment by Miosame** [comment]
PR done: https://github.com/DylanPiercey/local-devices/pull/24
