### ISSUE TITLE
arp -a not found on raspberry pi(balena os iot)

### ISSUE THREAD

**Issue by edo92** [DylanPiercey/local-devices#25]
Error: arp -a not found when runing on raspberry pi

**Comment by natterstefan** [comment]
Hi @edo92, I've no experience with balenaOS, sorry. I wrote them on twitter and hopefully they can help us resolving your issue. As soon as they write me, you'll get an update here.

**Comment by AdamKearn** [comment]
@edo92 If BalenaOS works like other Linux distros then you just need to run this command.
```
sudo apt-get install net-tools
```

**Comment by edo92** [comment]
Yes which goes in dockerfile
