### ISSUE TITLE
Arp -a table for react-native?

### ISSUE THREAD

**Issue by Eduardo-Maia98** [DylanPiercey/local-devices#29]
Hi, i'm doing a RN project, and I want to create a arp table of the local network , this libary is perfect for me, but it works on react-native?
Sorry, I'm a layman in this regard

**Comment by RichardRNStudio** [comment]
Hi, I would like to use this package with React Native as well, do you have any updates?

**Comment by DylanPiercey** [comment]
Duplicate of https://github.com/DylanPiercey/local-devices/issues/58 (although your issue was first)
