### ISSUE TITLE
does not list active devices.

### ISSUE THREAD

**Issue by gurselk** [DylanPiercey/local-devices#3]
Why is it listed after pinging the device?

**Comment by DylanPiercey** [comment]
I don’t know what you are asking. Please provide more details, expected output, actual output, etc.

**Comment by gurselk** [comment]
<img width="317" alt="ekran resmi 2018-05-13 12 39 16" src="https://user-images.githubusercontent.com/2247868/39965901-bac9efb4-56aa-11e8-9042-afa7a410dc84.png">

<img width="490" alt="ekran resmi 2018-05-13 12 41 04" src="https://user-images.githubusercontent.com/2247868/39965912-f65d1e84-56aa-11e8-9a1c-7fec3013d570.png">
<img width="479" alt="ekran resmi 2018-05-13 12 41 14" src="https://user-images.githubusercontent.com/2247868/39965913-f9815ed6-56aa-11e8-8e97-b2911a7f27dd.png">


Gamze-iPhoneu-Wireless does not appear


4 devices instead of 6 devices

**Comment by DylanPiercey** [comment]
Does the computer you are running the script on have access to both an interface connected to your WLAN and your Ethernet connections? Otherwise it will not see everything.

**Comment by DylanPiercey** [comment]
Closing this unless you have more info to provide. I would recommend trying 2.0.0 which supports more platforms.
