### ISSUE TITLE
Doesn't work on Homebridge running on Win10: Error: Command failed: arp -n 192.168.0.152

### ISSUE THREAD

**Issue by jsiegenthaler** [DylanPiercey/local-devices#37]
arp -n ipaddress

Result:
Error: Command failed: arp -n 192.168.0.152

arp -n 192.168.0.152 works fine on node on linux (raspberry pi)
but not on Windows Win10, it throws:
Error: Command failed: arp -n 192.168.0.152

**Comment by MisterSandFR** [comment]
same error here

**Comment by DylanPiercey** [comment]
You need to have arp installed. If it's not at a known path you can set the `arpPath` option.
